---
# token and master IP variables

#ideally, obtain the JWT for the service account from the command-line on the fly
#
#- name: obtain and store JWT for ansible service account
#  command: oc sa get-token ansible -n myproject
#  register: command_output 
#


token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiYW5zaWJsZS10b2tlbi1kcmNzcCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhbnNpYmxlIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNWQwOWFjYzgtMjNhNS0xMWU4LWIwOGEtMDgwMDI3YzgxZDkyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om15cHJvamVjdDphbnNpYmxlIn0.RmYQegDUi09t6_llOehcmlQSbI3TtACfUvTgu5tidiRNBgUfuqm7CTVM03nesQy7scES04lAcCpw3-t-4YAB3u2lo4c3rggm8ycDlTSpY2ozFI22ysoQqJ-dS6URDfr3_autDpDLHtiZjIzD7b-G8eP9vxLskBN-ZvWWW8CPluvZru4nJ-AZaM6Kss1rtVFDS0NKCRtNab-CeRcIXAk3NW6CksxKNV3zaefgy95LPZtT-QZw3Bwr24NPVR_XJ_b3Uh4ondcKwOOAHLaWUr_jQc-_zENbEpIE62oWz_7m-N1cAkTwrWpKXGnWXkKngdkSN8jDSisG5lMBFkuTKvZ9Cg
 
master_url: 192.168.99.106
